### ISSUE TITLE
Instalação

### ISSUE THREAD

**Issue by marcelloinfoweb** [saulotarsobc/oluas_proxmox#4]
Prezado, como instalo e busco as informações no Zabbix?

**Comment by saulotarsobc** [comment]
Opa. Mano. É só importar o template para o zabbix e vincular ele no host e
ajustar as macros. 😉

Em seg., 8 de jan. de 2024 18:25, marcelloinfoweb ***@***.***>
escreveu:

**Comment by marcelloinfoweb** [comment]
Falo em consideração ao grafana pra deixar como está na imagem.

**Comment by marcelloinfoweb** [comment]
Estou usando Proxmox 8, Zabbix 6.0 e Grafana 10.

Pretendo atualizar os arquivos?

**Comment by saulotarsobc** [comment]
> Estou usando Proxmox 8, Zabbix 6.0 e Grafana 10.
> 
> Pretendo atualizar os arquivos?

Deveriam permanecer funcionais. Deu erro? Vou verificar rsrs

**Comment by marcelloinfoweb** [comment]
Infelizmente com seus arquivos não funcionou bem.

O que funcionou pra mim: https://www.zabbix.com/br/integrations/proxmox

versão 6.0
